### ISSUE TITLE
Trouble with running

### ISSUE THREAD

**Issue by khrigo** [seunkoko/bank_application_api#15]
I have this error after `flask db upgrade`:

`TypeError: coercing to Unicode: need string or buffer, PosixPath found`

**Comment by seunkoko** [comment]
Hello @khrigo, can I get more insight on this bug?

Also, to confirm, did you add your `DATABASE_URI` in the `.env` file? If not, you can go to api.elephantsql.com to create a database instance, then get your `url` to add in the code.

Another thing to take note of is that this code was written in python2 and using pip for installations, so be sure to follow these rules. I might find the time to upgrade to python3 soon though.

Side Note: I will be updating the dependencies flagging security errors, so you might want to update your code.

Elephant SQL db instance ---> All you need is the `url`
<img width="763" alt="Screen Shot 2020-07-14 at 1 22 33 PM" src="https://user-images.githubusercontent.com/13197845/87414892-176dd000-c5d5-11ea-9222-f06921ea1256.png">

Then add in your code to look like this
<img width="759" alt="Screen Shot 2020-07-14 at 1 24 03 PM" src="https://user-images.githubusercontent.com/13197845/87415060-4b48f580-c5d5-11ea-913b-61f2c22b33fa.png">

**Comment by khrigo** [comment]
Ok, I have a problem with DB.

**Comment by khrigo** [comment]
`No application found. Either work inside a view function or push an application context`

That after `new_user.save()`

**Comment by khrigo** [comment]
```
    new_user.save()
  File "/models.py", line 20, in save
    db.session.add(self)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 1022, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 3286, in __call__
    return self.class_(**local_kw)
  File "/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```
